# -*- coding: utf-8 -*-
"""Vagner.Atividades.Alura.12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KB-ntRlW2dhlPMooiOKvsXO_czVPTyuU
"""

class TributavelMixIn:
    def get_valor_imposto(self):
        pass


class Conta:
    def __init__(self, numero, titular, saldo=0.0):
        self._numero = numero
        self._titular = titular
        self._saldo = saldo

    def deposita(self, valor):
        self._saldo += valor

    def saca(self, valor):
        self._saldo -= valor

    def get_saldo(self):
        return self._saldo


class ContaCorrente(Conta, TributavelMixIn):
    def get_valor_imposto(self):
        return self._saldo * 0.01


class SeguroDeVida(TributavelMixIn):
    def __init__(self, valor, titular, numero_apolice):
        self._valor = valor
        self._titular = titular
        self._numero_apolice = numero_apolice

    def get_valor_imposto(self):
        return 50 + self._valor * 0.05


class ManipuladorDeTributaveis:
    def calcula_impostos(self, lista_tributaveis):
        total = 0
        for t in lista_tributaveis:
            total += t.get_valor_imposto()
        return total


# Execução dos testes
if __name__ == '__main__':
    cc1 = ContaCorrente('001', 'Vagner', 1000.0)
    cc2 = ContaCorrente('002', 'Eduardo', 2000.0)
    seguro1 = SeguroDeVida(100.0, 'Eduardo', '111-22')
    seguro2 = SeguroDeVida(200.0, 'Rafael', '333-44')

    lista_tributaveis = [cc1, cc2, seguro1, seguro2]

    manipulador = ManipuladorDeTributaveis()
    total = manipulador.calcula_impostos(lista_tributaveis)

    print(f"Total de impostos: R${total:.2f}")