# -*- coding: utf-8 -*-
"""Vagner.Atividades.Alura.9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IPfbG_kCF4d88TvuB0XUOMoxECNv5nfH
"""

class Conta:
    __slots__ = ['_numero', '_titular', '_saldo', '_limite', 'identificador']

    _contador = 0

    def __init__(self, numero, titular, saldo, limite=1000.0):
        Conta._contador += 1
        self.identificador = Conta._contador
        self._numero = numero
        self._titular = titular
        self._saldo = saldo
        self._limite = limite

    @property
    def numero(self):
        return self._numero

    @property
    def titular(self):
        return self._titular

    @property
    def saldo(self):
        return self._saldo

    @saldo.setter
    def saldo(self, valor):
        if valor >= 0:
            self._saldo = valor
        else:
            print("Saldo não pode ser negativo.")

    @property
    def limite(self):
        return self._limite

    @limite.setter
    def limite(self, valor):
        if valor >= 0:
            self._limite = valor
        else:
            print("Limite não pode ser negativo.")

    def __str__(self):
        return (f"ID: {self.identificador}, Conta: {self._numero}, Titular: {self._titular}, "
                f"Saldo: R${self._saldo}, Limite: R${self._limite}")

#TESTANDO!
conta1 = Conta(123, "Vagner", 500.0)
conta2 = Conta(456, "Vagner pai", 800.0)
conta3 = Conta(789, "Vagner irmã", 1200.0)

print(conta1)
print(conta2)
print(conta3)