# -*- coding: utf-8 -*-
"""Vagner.Atividades.Alura.13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9iY9_MFnOs_mXqTPpp1k-yFHNL1KKBR
"""

# Exceção personalizada
class SaldoInsuficienteError(RuntimeError):
    pass


# Classe base Conta
class Conta:
    def __init__(self, numero, titular, saldo=0.0):
        self._numero = numero
        self._titular = titular
        self._saldo = saldo

    def deposita(self, valor):
        if valor < 0:
            raise ValueError('Você tentou depositar um valor negativo.')
        self._saldo += valor

    def saca(self, valor):
        if valor < 0:
            raise ValueError('Você tentou sacar um valor negativo.')
        if self._saldo < valor:
            raise SaldoInsuficienteError('Saldo insuficiente.')
        self._saldo -= valor

    def get_saldo(self):
        return self._saldo


# Conta Corrente
class ContaCorrente(Conta):
    def saca(self, valor):
        if valor < 0:
            raise ValueError('Você tentou sacar um valor negativo.')
        if self._saldo < valor + 0.10:
            raise SaldoInsuficienteError('Saldo insuficiente.')
        self._saldo -= (valor + 0.10)


# Conta Poupança
class ContaPoupanca(Conta):
    def deposita(self, valor):
        if valor < 0:
            raise ValueError('Você tentou depositar um valor negativo.')
        self._saldo += valor


# Testes
if __name__ == '__main__':
    # Teste com Vagner
    cc_vagner = ContaCorrente('001', 'Vagner', 1000.0)

    print("\n[ Vagner ]")
    try:
        cc_vagner.saca(-100.0)
    except ValueError:
        print('O valor a ser sacado deve ser um número positivo.')

    try:
        cc_vagner.saca(2000.0)
    except ValueError:
        print('O valor a ser sacado deve ser um número positivo.')
    except SaldoInsuficienteError:
        print('Você não possui saldo suficiente para concluir esta operação.')

    try:
        cc_vagner.deposita(-500.0)
    except ValueError:
        print('O valor a ser depositado deve ser um número positivo.')

    # Teste com Eduardo
    cc_eduardo = ContaCorrente('002', 'Eduardo', 1500.0)

    print("\n[ Eduardo ]")
    try:
        cc_eduardo.saca(1400.0)
        print(f'Saldo restante de Eduardo: R${cc_eduardo.get_saldo():.2f}')
    except Exception as e:
        print(f'Erro: {e}')

    # Teste com Rafael
    cp_rafael = ContaPoupanca('003', 'Rafael', 500.0)

    print("\n[ Rafael ]")
    try:
        cp_rafael.deposita(-100)
    except ValueError:
        print('O valor a ser depositado deve ser um número positivo.')

    try:
        cp_rafael.saca(700)
    except SaldoInsuficienteError:
        print('Você não possui saldo suficiente para concluir esta operação.')